### ISSUE TITLE
Missing Library libjpeg.so.9

### ISSUE THREAD

**Issue by mgerald21** [cjj25/RTS3903N-Tools#2]
Hi,

just noticed that command v4l2grab references a libjpeg which is missing in repo.

```
/var/tmp/sd/app # ./v4l2grab 
./v4l2grab: can't load library 'libjpeg.so.9'
```

KR, GM

**Comment by code-explorer1234** [comment]
Added library for you - pls test.

**Comment by code-explorer1234** [comment]
I'm also curious to know what you're building / working on :-)

**Comment by mgerald21** [comment]
I just tried to run the available tools to see if there was anything useful.
In the end I'd like to see https://github.com/jacksonliam/mjpg-streamer running on the camera.
