### ISSUE TITLE
IR cut filter is not working using gpio controls, board is DCS-8630LH

### ISSUE THREAD

**Issue by veermit** [cjj25/RTS3903N-Tools#3]
I'm using the board DCS-8630LH, I have a GPL code, in that with  example_day_night_mode I tried to record the stream, but I observed in indoor it's fine but while I recorded in outdoor condition it was pinkish colour.

As per code code is trying to toggle GPIO for IR light and IR CUT filter, but it's not at all working.

Did you faced this kind of issues?

Please help me on this thread.

**Comment by code-explorer1234** [comment]
Have you identified the correct GPIO pin for the ADC / IR CUT?

Do you hear the typical "click" when its activated?

**Comment by code-explorer1234** [comment]
See my other repo and the [relevant code I put together around this.](https://github.com/cjj25/Yi-RTS3903N-RTSPServer/blob/7763840399c08659c6b2e875bc4bca5a30f7f58b/build/src/stream.c#L138)

**Comment by veermit** [comment]
Can you guide me how can I identify the correct mapped GPIO, form data sheets its 86 pin which came out from SoC for IC cut.?

The click sound only observed when isp initialised. Rather than that while toggling GPIO that time not observed any click sound.

**Comment by veermit** [comment]
open("/dev/cpld_periph", O_RDWR); this is not present in my device, to manage IR cut, whether I need to enable any option in SDK.?? To get this node. Cpld_periph?

**Comment by code-explorer1234** [comment]
You're right! I completely forgot. The cpld_periph was a driver written by YI that gets added on boot. I used it in that repo so I wouldn't have to figure out the GPIO pins for everyones cameras.

I used [strace](https://github.com/cjj25/RTS3903N-Tools/blob/master/strace) to sniff all the binaries that came with the camera and discovered the calls its made. I highly recommend you give this a shot, you'll be able to see the calls being made for the IR cut etc.

There's some[ commented out code](https://github.com/cjj25/Yi-RTS3903N-RTSPServer/blob/7763840399c08659c6b2e875bc4bca5a30f7f58b/build/src/stream.c#L84) here that (I think) worked when I knew the exact GPIO pins.


>>> The click sound only observed when isp initialised.

Sounds like you know one of the pins already!

**Comment by veermit** [comment]
Thank you so much for your valuable response, will also try to use strace to sniff. I am just able to identify the click sound but not able to identify the exact GPIO. I have tried toggling the GPIOs which is available free but I didn't receive any response from IR cut filter.

**Comment by code-explorer1234** [comment]
You're welcome - could you provide a firmware dump? I might be able to find the pinouts.

**Comment by veermit** [comment]
Can you plz ping me over the meet, satyaveer000@gmail.com. 

Techwaliya (satyaveer)

**Comment by code-explorer1234** [comment]
I've messaged you on Google Chat.

**Comment by code-explorer1234** [comment]
Resolved.
`Domain is 1 and IO is also 1 for IR CUT`
